FROM golang:1.25.5-alpine

WORKDIR /app

RUN apk add --no-cache git gcc musl-dev ffmpeg
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["air", "-c", ".air.toml"]